RosaliaNightsong/discord-bot

- CONTRIBUTING.md
- README.md
Add the specific information to the README template and expand
contributing documentation.
Closes #XXXXX
> feat(docs): add project info

- package-lock.json
- package.json
- src/config/IntentOptions.ts
- src/index.ts
Upgrade to `discord.js` version 13.
Closes #XXXXX
> feat: migrate discord

- src/index.ts
Forgot to update deprecated event name.
Closes #XXXXX
> fix: message → messageCreate

- .eslintrc.json
- .huskyrc
- package-lock.json
- package.json
- src/commands/_CommandList.ts
- src/commands/slime.ts
- src/events/onMessage.ts
- src/events/onReady.ts
- src/helpers/logHandler.ts
- src/index.ts
Update the deps, apply new lint rules
Closes #XXXXX
> feat: deps

- sample.env
- src/database/connectDatabase.ts
- src/database/models/CharacterModel.ts
- src/index.ts
- src/interfaces/RosaliaNightsong.ts
- src/interfaces/game/Adventure.ts
- src/interfaces/game/Character.ts
- src/interfaces/game/Consumable.ts
- src/interfaces/game/Equipment.ts
- src/interfaces/game/Monster.ts
- src/interfaces/game/Sellable.ts
- src/utils/validateEnv.ts
Define the type definitions for the expected data, and set up the database connection.
Closes #75 
Closes #76 
Closes #93 
Closes #94 
Closes #85 
Closes #88
> chore: establish type defs

- src/commands/rosalia.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleDonate.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/utils/getCounts.ts
Build out three of the four expected `/rosalia` commands.
Closes #97 
Closes #100 
Closes #99
> feat: rosalia commands

- src/commands/character.ts
- src/modules/subcommands/character/handleCreate.ts
- src/modules/subcommands/character/handleUpdate.ts
- src/modules/subcommands/character/handleView.ts
- src/modules/viewCharacter.ts
Add the `/character` commands.
Closes #77 
Closes #78 
Closes #79
> feat: character commands

- package-lock.json
- package.json
- src/config/data/adventures.ts
- src/config/data/consumables.ts
- src/config/data/equippables.ts
- src/config/data/monsters.ts
- src/config/data/sellables.ts
- src/interfaces/game/Adventure.ts
- src/interfaces/game/Monster.ts
- src/modules/subcommands/character/handleCreate.ts
- test/data.spec.ts
- tsconfig.json
Add some seed data, and include tests.
Closes #95
> feat: seed data

- src/commands/character.ts
- src/commands/inventory.ts
- src/database/models/CharacterModel.ts
- src/interfaces/game/Character.ts
- src/modules/subcommands/character/handleCreate.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
Adds the inventory-related commands.
Closes #80 
Closes #81 
Closes #82 
Closes #96
> feat: inventory commands

- src/commands/adventure.ts
- src/config/data/equippables.ts
- src/config/data/restOptions.ts
- src/interfaces/game/Equipment.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleDungeon.ts
- src/modules/subcommands/adventure/handleExplore.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- test/data.spec.ts
Closes #84 
Closes #86 
Closes #87 
Closes #92
> feat: adventure commands

- src/config/data/levelScale.ts
- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/subcommands/adventure/handleDungeon.ts
- src/modules/subcommands/adventure/handleExplore.ts
Closes #89 
Closes #90 
Closes #91
> feat: battle system

- src/commands/rosalia.ts
- src/modules/subcommands/rosalia/handleHelp.ts
> feat: help command

- package-lock.json
- package.json
> release: 0.0.1-rc.0

- src/database/models/CharacterModel.ts
Discord ID was in the interface but not the actual schema.
Closes #XXXXX
> fix: add discordId to schema

- src/database/models/CharacterModel.ts
- src/interfaces/game/Character.ts
- test/schema.spec.ts
TypeScript doesn't seem to catch that the schema has all of the expected properties on the interface. 
This PR creates a test `Character` object (which TypeScript does validate) and tests that every property on the test object exists on the model.
Closes #XXXXX
> chore(tools): test character schema

- README.md
Add a brief note about hacktoberfest participation
Closes #XXXXX
> docs: contributing note

- package-lock.json
- package.json
> release: 0.0.1-rc.1

- src/modules/subcommands/adventure/handleDungeon.ts
- src/modules/subcommands/adventure/handleExplore.ts
Added `character.markModified(adventure);` in `handleDungeon.ts` and `handleExplore.ts` to fix improper cooldown saving bug (#124)
Closes #124
> Fix improper cooldown saving bug #124

- src/commands/rosalia.ts
- src/config/betaTesters.ts
- src/modules/subcommands/rosalia/handleBeta.ts
Add a command to display thanks to our wonderful beta testers.
Closes #XXXXX
> feat: beta command

- package-lock.json
- package.json
- src/index.ts
- src/server/createServer.ts
Creates an Express server for uptime monitoring.
Closes #XXXXX
> feat: create http server

- package-lock.json
- package.json
Time to make it public!
Closes #XXXXX
> release: v1.0.0

- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
- src/modules/subcommands/market/handleVisit.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleBeta.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handlePing.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/viewCharacter.ts
- src/utils/errorEmbedGenerator.ts
Add a donation CTA to the embeds.
Closes #XXXXX
> feat: add donation cta

- package-lock.json
- package.json
> release: v1.0.1

- package-lock.json
- package.json
- src/utils/getCounts.ts
> chore: package updates

- src/database/connectDatabase.ts
- src/events/onGuildCreate.ts
- src/events/onGuildDelete.ts
- src/events/onReady.ts
- src/index.ts
- src/modules/subcommands/character/handleCreate.ts
- src/modules/subcommands/rosalia/handleAbout.ts
Add logging for guild join/leave, character creation, and clean up logging for ready events.
Also add total character count to about embed.
Closes #XXXXX
> feat: improve logging

- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
- src/modules/subcommands/market/handleVisit.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleBeta.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handlePing.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/viewCharacter.ts
- src/utils/errorEmbedGenerator.ts
> feat: add avatar to embed footers

- package-lock.json
- package.json
> release: v1.1.1

- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handleProfile.ts
> feat: use buttons in embeds

- src/commands/rosalia.ts
- src/modules/subcommands/rosalia/handleContact.ts
Adds a new `/rosalia contact` command.
Closes #XXXXX
> feat: add contact command

- src/commands/rosalia.ts
- src/config/data/updates.ts
- src/interfaces/RosaliaNightsong.ts
- src/modules/subcommands/rosalia/handleUpdates.ts
- src/utils/validateEnv.ts
Adds a `/rosalia updates` command to display the changelog since the last release.
Closes #XXXXX
> feat: updates command

- package-lock.json
- package.json
- src/config/data/updates.ts
> release: v1.2.0

- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/subcommands/rosalia/handleUpdates.ts
> feat: add utms

- src/modules/subcommands/rosalia/handleAbout.ts
Added a style value to the inviteButton to fix the /rosalia about command throwing an error
Closes #321
> fix /rosalia about command

- package-lock.json
- package.json
- src/config/data/updates.ts
> release: v1.2.1

- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
- src/modules/subcommands/market/handleVisit.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleBeta.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handlePing.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/subcommands/rosalia/handleUpdates.ts
- src/modules/viewCharacter.ts
- src/utils/errorEmbedGenerator.ts
> chore: update avatar

- package-lock.json
- package.json
- src/config/data/updates.ts
> release: v2.0.0

- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
- src/modules/subcommands/market/handleVisit.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleBeta.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handlePing.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/viewCharacter.ts
- src/utils/errorEmbedGenerator.ts
> chore: replace embed footer link

- src/modules/battle/handleBattle.ts
- src/modules/battle/results/battleDefeat.ts
- src/modules/battle/results/battleFlee.ts
- src/modules/battle/results/battleMonsterFlee.ts
- src/modules/battle/results/battleVictory.ts
- src/modules/results/giveDungeon.ts
- src/modules/results/giveItem.ts
- src/modules/results/showCooldown.ts
- src/modules/subcommands/adventure/handleMap.ts
- src/modules/subcommands/adventure/handleRest.ts
- src/modules/subcommands/character/handleEquipment.ts
- src/modules/subcommands/inventory/handleDetails.ts
- src/modules/subcommands/inventory/handleSell.ts
- src/modules/subcommands/inventory/handleUse.ts
- src/modules/subcommands/inventory/handleView.ts
- src/modules/subcommands/inventory/uses/consumeItem.ts
- src/modules/subcommands/inventory/uses/equipItem.ts
- src/modules/subcommands/market/handleVisit.ts
- src/modules/subcommands/rosalia/handleAbout.ts
- src/modules/subcommands/rosalia/handleArt.ts
- src/modules/subcommands/rosalia/handleBeta.ts
- src/modules/subcommands/rosalia/handleHelp.ts
- src/modules/subcommands/rosalia/handlePing.ts
- src/modules/subcommands/rosalia/handleProfile.ts
- src/modules/viewCharacter.ts
- src/utils/errorEmbedGenerator.ts
> chore: no custom link

- src/config/data/updates.ts
- src/modules/subcommands/rosalia/handleUpdates.ts
> fix: tweak layout of updates command

- package-lock.json
- package.json
- src/config/data/updates.ts
> release: v2.0.1

- src/modules/subcommands/rosalia/handleContact.ts
> chore: replace twitter links with mastodon

- src/modules/subcommands/rosalia/handleArt.ts
Updated the `artEmbed.setImage` URL from:
- `https://www.rosalianightsong.com/assets/art/${art.fileName.replace(/\s/g, "%20")}`
to the new CDN link:
- `https://cdn.naomi.lgbt/rosalia/art/${art.fileName.replace(/\s/g, "%20")}`
I also ran my local development version on my discord test server to verify
Closes #570 
<details>
<summary><strong>Click here</strong> to see visual verification of changes</summary>
<br>
<p>After running `npm run prebuild`, `npm run build`, and `npm run start`</p>
<h3>Visual verification of after running `npm run start`</h3>
<h3>Visual verification of discord bot connection to test discord server and `/rosalia art`</h3>
<h3>Verification of the `cdn.naomi.lgbt` CDN URL</h3>
</details>
<details>
<summary><strong>Click here</strong> to see how I am feeling</summary> …
> CHORE: update image CDN URL
